### ISSUE TITLE
Reorganize the Documentation

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/vmc#30]
Brainstorm on the outline/sections needed to make a good structure for scalability and dissemination.

**Comment by larrybabb** [comment]
[GKS Deliverable Roadmap](https://docs.google.com/presentation/d/1zjZrXuqMEJkAQy82nh5z8UKPKSnl9UKWG17sTO12T08/edit#slide=id.p)

**Comment by reece** [comment]
Duplicate of #19. Closing.
